import React from 'react';
import { DailyPlan, UserProfile, Sku } from '../../types';
import { EditIcon } from '../icons/EditIcon';
import { WhatsAppIcon } from '../icons/WhatsAppIcon';

interface DailyPlanViewProps {
    plan: DailyPlan;
    user: UserProfile;
    onEditBaseline: () => void;
    onNewCheckin: () => void;
}

const SKU_COLORS: Record<Sku, { bg: string, text: string, border: string }> = {
    "Gutrify": { bg: 'bg-green-100 dark:bg-green-900/40', text: 'text-green-800 dark:text-green-300', border: 'border-green-500' },
    "FiberFuel": { bg: 'bg-yellow-100 dark:bg-yellow-900/40', text: 'text-yellow-800 dark:text-yellow-300', border: 'border-yellow-500' },
    "ObeCalm": { bg: 'bg-blue-100 dark:bg-blue-900/40', text: 'text-blue-800 dark:text-blue-300', border: 'border-blue-500' },
    "LeanPulse": { bg: 'bg-red-100 dark:bg-red-900/40', text: 'text-red-800 dark:text-red-300', border: 'border-red-500' },
    "MetaboFix": { bg: 'bg-purple-100 dark:bg-purple-900/40', text: 'text-purple-800 dark:text-purple-300', border: 'border-purple-500' },
};

const ScoreDisplay: React.FC<{label: string, value: number}> = ({label, value}) => {
    const color = value >= 70 ? 'text-red-500' : value >= 50 ? 'text-yellow-500' : 'text-green-500';
    const width = `${Math.min(100, value)}%`;
    return (
        <div className="text-center">
            <div className={`text-3xl font-bold ${color}`}>{Math.round(value)}</div>
            <div className="text-xs font-semibold text-gray-500 dark:text-gray-400">{label}</div>
            <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-1 mt-1">
                <div className={`h-1 rounded-full ${color.replace('text','bg')}`} style={{width}}></div>
            </div>
        </div>
    )
};


const DailyPlanView: React.FC<DailyPlanViewProps> = ({ plan, user, onEditBaseline, onNewCheckin }) => {
    
    const handleShare = () => {
        let shareText = `*ObeCure BioAdaptive Plan*\n\n`;
        shareText += `*Date:* ${new Date(plan.date + 'T00:00:00').toLocaleDateString('en-GB')}\n`;
        if (user.name) {
            shareText += `*For:* ${user.name}\n`;
        }
        shareText += `\n*Today's Phenotype:*\n- ${plan.phenotype.primary}${plan.phenotype.secondary ? ` / ${plan.phenotype.secondary}` : ''}\n`;

        shareText += `\n*Personalized Prescription:*\n`;
        plan.plan.forEach(item => {
            shareText += `- *${item.sku}®*: ${item.dose} at ${item.time}\n`;
        });

        if (plan.notes.length > 0) {
            shareText += `\n*Doctor's Notes:*\n`;
            plan.notes.forEach(note => {
                shareText += `- _${note}_\n`;
            });
        }

        shareText += `\nGenerated by ObeCure.`;

        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
        window.open(whatsappUrl, '_blank');
    };
    
    return (
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg border border-gray-100 dark:border-gray-700 animate-fade-in-up">
            <div className="flex justify-between items-start mb-4">
                <div>
                    <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-200">Your Plan for Today</h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400">{new Date(plan.date + 'T00:00:00').toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                </div>
                <div className="flex gap-2">
                     <button onClick={onEditBaseline} className="p-2 rounded-full bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors" title="Edit Bio-Profile">
                        <EditIcon className="w-5 h-5 text-gray-600 dark:text-gray-300" />
                    </button>
                    <button onClick={handleShare} className="p-2 rounded-full bg-green-100 dark:bg-green-900/40 hover:bg-green-200 dark:hover:bg-green-900/60 transition-colors" title="Share on WhatsApp">
                        <WhatsAppIcon className="w-5 h-5 text-green-600 dark:text-green-400" />
                    </button>
                </div>
            </div>

            <div className="p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg mb-6">
                <h3 className="font-bold text-center mb-3 text-gray-700 dark:text-gray-300">Your Metabolic Scores</h3>
                <div className="grid grid-cols-5 gap-4">
                    <ScoreDisplay label="Gut Load" value={plan.scores.GLS} />
                    <ScoreDisplay label="Appetite" value={plan.scores.ACS} />
                    <ScoreDisplay label="Stress" value={plan.scores.SCS} />
                    <ScoreDisplay label="Energy" value={plan.scores.EDS} />
                    <ScoreDisplay label="Metabolism" value={plan.scores.MSS} />
                </div>
            </div>

            <div className="text-center mb-6">
                <h3 className="font-bold text-gray-700 dark:text-gray-300">Today's Phenotype</h3>
                <p className="text-xl font-semibold text-orange-600 dark:text-orange-400">
                    {plan.phenotype.primary}
                    {plan.phenotype.secondary && <span className="text-base text-gray-500 dark:text-gray-400"> / {plan.phenotype.secondary}</span>}
                </p>
            </div>

            <div className="space-y-4">
                {plan.plan.map(item => (
                    <div key={item.sku} className={`p-4 rounded-lg border-l-4 ${SKU_COLORS[item.sku].bg} ${SKU_COLORS[item.sku].border}`}>
                        <div className="flex justify-between items-start">
                             <div>
                                <h4 className={`font-bold text-lg ${SKU_COLORS[item.sku].text}`}>{item.sku}®</h4>
                                <p className="font-semibold text-gray-800 dark:text-gray-200">{item.dose} at {item.time}</p>
                             </div>
                        </div>
                        <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">{item.reason}</p>
                        {item.caution && <p className="text-xs text-red-600 dark:text-red-400 mt-2 font-semibold">Caution: {item.caution}</p>}
                    </div>
                ))}
            </div>

            {plan.notes.length > 0 && (
                 <div className="mt-6">
                    <h4 className="font-bold text-gray-700 dark:text-gray-300 mb-2">Doctor's Notes</h4>
                    <ul className="list-disc list-inside space-y-1 text-sm text-gray-600 dark:text-gray-400 bg-gray-50 dark:bg-gray-700/50 p-4 rounded-lg">
                        {plan.notes.map((note, i) => <li key={i}>{note}</li>)}
                    </ul>
                </div>
            )}
            
            <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
                <button onClick={onNewCheckin} className="w-full bg-orange-500 text-white font-bold py-3 px-6 rounded-lg hover:bg-orange-600 transition-all active:scale-95 shadow-md">
                    Update Today's Check-in
                </button>
            </div>
        </div>
    )
}

export default DailyPlanView;